# Generated by Django 5.2.5 on 2025-08-20 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receita',
            name='time_coking',
        ),
    ]
