# Generated by Django 5.2.5 on 2025-08-20 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0002_remove_receita_time_coking'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='time_coking',
            field=models.IntegerField(default=1, help_text='Em minutos'),
            preserve_default=False,
        ),
    ]
