# Generated by Django 5.2.5 on 2025-08-20 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0003_receita_time_coking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receita',
            name='time_coking',
        ),
    ]
